apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-run-
spec:
  serviceAccountName: myadmin
  pipelineRef:
    name: my-git-clone
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
  - name: repo-url
    value: git@github.com:tt5/p-website-chess.git
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
