apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-run-
spec:
  pipelineRef:
    name: my-git-clone
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
  - name: repo-url
    value: https://github.com/tt5/l-js-solidstart-chess.git
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: workspace
