apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test
spec:
  serviceAccountName: myadmin
  taskRunSpecs:
  - pipelineTaskName: test-install
    taskServiceAccountName: myadmin
  pipelineRef:
    name: test
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
