apiVersion: v1
kind: Pod
metadata:
  name: wolfi
spec:
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: workspace
  containers:
  - name: wolfi
    image: cgr.dev/chainguard/wolfi-base 
    tty: true
    stdin: true
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - mountPath: "/home"
      name: storage
